version: '3.8'

services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    volumes:
      - ./bot:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
