# Generated by Django 4.2.13 on 2024-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_discount_options_alter_place_options'),
        ('user', '0002_user_fav_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_places',
            field=models.ManyToManyField(blank=True, to='discounts.place', verbose_name='Избранные места'),
        ),
    ]
