# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_discount_place_type_alter_discount_place'),
        ('user', '0003_alter_user_fav_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_places',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_discounts',
            field=models.ManyToManyField(blank=True, to='discounts.discount', verbose_name='Избранные скидки'),
        ),
    ]
