# Generated by Django 4.2.13 on 2024-07-22 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('token', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
