# Generated by Django 4.2.13 on 2024-07-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_passwordrecoveryrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRecoveryRequest',
        ),
    ]
