# Generated by Django 4.2.13 on 2024-07-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_passwordrecoveryrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
