# Generated by Django 4.2.13 on 2024-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscription_created_at_subscription_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_sub_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Идентификатор подписки CloudPayments'),
        ),
    ]
