# Generated by Django 4.2.13 on 2024-08-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscription_payment_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_sub_id',
        ),
    ]
