# Generated by Django 4.2.13 on 2024-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_subscription_payment_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Номер в боте'),
        ),
    ]
