# Generated by Django 4.2.13 on 2024-10-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscription_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='order',
        ),
    ]
