# Generated by Django 4.2.13 on 2024-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateField(verbose_name='Дата конца скидки'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала скидки'),
        ),
    ]
