# Generated by Django 4.2.13 on 2024-07-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_discount_end_date_alter_discount_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
    ]
