# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_discount_options_alter_place_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='place_type',
            field=models.CharField(blank=True, choices=[('RE', 'Ресторан'), ('CA', 'Кафе'), ('CF', 'Кофейня')], max_length=2, verbose_name='Тип заведения'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='place',
            field=models.CharField(max_length=50, verbose_name='Место'),
        ),
    ]
