# Generated by Django 4.2.13 on 2024-07-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_discount_place_type_alter_discount_place'),
        ('user', '0004_remove_user_fav_places_user_fav_discounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
