# Generated by Django 4.2.13 on 2024-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_discount_image_alter_discount_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='address_txt',
            field=models.CharField(blank=True, max_length=100, verbose_name=''),
        ),
    ]
