# Generated by Django 4.2.13 on 2024-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_discount_address_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='address_txt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
    ]
