# Generated by Django 4.2.13 on 2024-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0009_alter_discount_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Номер в боте'),
        ),
    ]
