# Generated by Django 4.2.13 on 2024-10-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_discount_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promocode',
            field=models.CharField(blank=True, max_length=60, verbose_name='Промокод'),
        ),
    ]
