# Generated by Django 4.2.13 on 2024-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_discount_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promocode_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание промокода'),
        ),
    ]
