# Generated by Django 4.2.13 on 2024-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_discount_promocode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='show_in_bot',
            field=models.BooleanField(default=False, verbose_name='Отображение в боте'),
        ),
        migrations.AddField(
            model_name='discount',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Отображение на сайте'),
        ),
    ]
