# Generated by Django 4.2.13 on 2024-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_discount_show_in_bot_discount_show_on_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='url',
            field=models.CharField(blank=True, default='', verbose_name='Ссылка партнера'),
        ),
    ]
