# Generated by Django 4.2.13 on 2024-11-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0014_discount_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Когда обновлено')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', verbose_name='Название')),
                ('lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='locations',
            field=models.ManyToManyField(blank=True, default='', null=True, to='discounts.place', verbose_name='Локации скидки'),
        ),
    ]
