# Generated by Django 4.2.13 on 2024-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_place_discount_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='place',
            new_name='place_name',
        ),
        migrations.AddField(
            model_name='place',
            name='discounts',
            field=models.ManyToManyField(blank=True, default='', null=True, to='discounts.discount', verbose_name='Скидки'),
        ),
    ]
