# Generated by Django 4.2.13 on 2024-11-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0015_place_discount_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, default='', verbose_name='Название'),
        ),
    ]
