# Generated by Django 4.2.13 on 2024-11-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='locations',
        ),
        migrations.AddField(
            model_name='discount',
            name='locations',
            field=models.ManyToManyField(blank=True, default='', to='discounts.place', verbose_name='Локации скидки'),
        ),
    ]
