# Generated by Django 4.2.13 on 2024-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0016_rename_place_discount_place_name_place_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='backpage_text',
            field=models.CharField(blank=True, default='', verbose_name='Текст на обороте'),
        ),
    ]
